version: '3.3'

services:
  recruitment-service-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_USER: user
      MYSQL_PASSWORD: newpassword
    ports:
    - '3306:3306'
    volumes:
    - recruitment-service-volume:/var/lib/mysql
    restart: on-failure

volumes:
  recruitment-service-volume:
    external: true
